name: Build Forum
on:
  push:
    branches:
      - "main"
      - "develop"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - run: cd backend && npm install
      - run: cd frontend && npm install
      - run: npm run build:full
      - uses: actions/upload-artifact@v3
        with:
          name: forum
          path: ${{ github.workspace }}/out
          retention-days: 2
